server:
  port: 8080

spring:
  application:
    name: Info Home

  datasource:
    url: jdbc:postgresql://localhost:5432/infohome
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql

    show-sql: true
    hibernate:
      ddl-auto: validate